version: '3'

services:
  nginx:
    build:
      context: ./setup/nginx
      dockerfile: Dockerfile-eventdata
    links:
      - rook-service:rook-service
      - ta3-main:ta3-main
    ports:
      - 80:80
    depends_on:
      - ta3-main
      - rook-service
    volumes:
      - ./ravens_volume:/ravens_volume
  rook-service:
    build:
      context: ./
      dockerfile: Dockerfile-eventdata-r-service
    environment:
      # Note: this variable is also set in Dockerfile-r-service
      - ROOK_USE_PRODUCTION_MODE=yes
    ports:
      - 8000
    volumes:
      - ./ravens_volume:/ravens_volume
  ta3-main:
    build:
      context: ./
      dockerfile: Dockerfile-eventdata
    environment:
      # If True, don't use an actual TA2, returned canned responses
      - TA2_STATIC_TEST_MODE=True
      # Example of specifying a TA2 service
      #- TA2_TEST_SERVER_URL=ta2-main:45042
      #- CONFIG_JSON_PATH=/ravens_volume/config_o_4550seed.json
      #- CONFIG_JSON_PATH=/ravens_volume/config_185_baseball.json
    links:
      - rook-service
    ports:
      # 8080: web service
      - 8080:8080
    volumes:
      - ./ravens_volume:/ravens_volume
