version: '3'

services:
  nginx:
    build:
      context: ./setup/nginx
      dockerfile: Dockerfile
    links:
      - rook-service:rook-service
      - tworavens:tworavens
    ports:
      - 80:80
    depends_on:
      - tworavens
      - rook-service
    volumes:
      - ./ravens_volume:/ravens_volume
  rook-service:
    build:
      context: ./
      dockerfile: Dockerfile-rook
    environment:
      # Note: this variable is also set in Dockerfile-rook
      - ROOK_USE_PRODUCTION_MODE=yes
    ports:
      - 8000
    volumes:
      - ./ravens_volume:/ravens_volume
  tworavens:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      # If True, don't use an actual TA2, returned canned responses
      - TA2_STATIC_TEST_MODE=False
      # Example of specifying a TA2 service
      - TA2_TEST_SERVER_URL=ta2-main:50051
      #- CONFIG_JSON_PATH=/ravens_volume/config_o_4550seed.json
      - CONFIG_JSON_PATH=/ravens_volume/config_o_196.json
    links:
      - rook-service
    ports:
      # 8080: web service
      - 8080:8080
    volumes:
      - ./ravens_volume:/ravens_volume
  ta2-main:
    image: registry.datadrivendiscovery.org/ta2/isi_ta2:latest
    environment:
      - CONFIG_JSON_PATH=/ravens_volume/config_o_196.json
    volumes:
      - ./ravens_volume:/ravens_volume
    ports:
      # 50051: grpc connection
      - 50051:50051
